📝 Upgrade docs
Pincer-org/Pincer pull request #155
Opened 2021-10-18 13:29 UTC by ooliver1

### Changes

-   `adds`: More docstrings
-   `fixed`: closes #86 and closes #83
-   `improvements`: Better numpy docstrings with the RestructuredText also changed

 ### Check off the following

-   [x] I have tested my changes with the current requirements
-   [x] My Code follows the pep8 code style.

Linted and fixed with autopep8 and flake8, line endings are all LF.

https://pincer-upgraded-docs.rtfd.io

2021-10-18 17:12 UTC, Sigmanificient commented
Holy!

2021-10-30 21:54 UTC, Lunarmagpie commented on pincer/utils/directory.py
> +    chdir(path)
This and the `chdir` after it are supposed to be `os.chrdir`. Its been fixed on my pr but I think the maintainers should take another look at this to make sure that the code styling is right.

2021-10-31 11:50 UTC, ooliver1 commented on pincer/middleware/__init__.py
> +
i have an idea on how to refactor it

2021-10-31 11:50 UTC, ooliver1 commented on pincer/middleware/__init__.py
> +)
i have an idea on how to refactor it

2021-10-31 11:55 UTC, ooliver1 commented on pincer/objects/guild/channel.py
> -    def mention(self) -> str:
it subclasses channel, i dont remember moving it but yeah

2021-10-31 11:59 UTC, Lunarmagpie commented on pincer/exceptions.py
> +class NotFoundError(HTTPError):
This is fixed now

2021-10-31 12:00 UTC, Lunarmagpie commented on pincer/utils/__init__.py
> +    "should_pass_cls", "should_pass_ctx", "MissingType", "get_params"
This is fixed now

2021-10-31 12:05 UTC, ooliver1 commented on pincer/objects/guild/guild.py
> +    hub_type: APINullable[...] = MISSING
changed in next commit

2021-10-31 13:49 UTC, trag1c approved these changes

2021-10-31 14:27 UTC, Arthurdw commented
_(**Current implementation is broken**)_

2021-11-01 19:09 UTC, Arthurdw requested changes

2021-11-01 19:09 UTC, Arthurdw commented on pincer/middleware/interaction_create.py
> -    await interaction.build()
Revert this removal.

2021-11-01 19:09 UTC, Arthurdw commented on pincer/objects/guild/guild.py
> -        """
Revert docs removal.

2021-11-01 19:09 UTC, Arthurdw commented on pincer/utils/__init__.py
> -    "APINullable", "APIObject", "Choices", "Coro", "Descripted",
Why did Descripted get removed?

2021-11-01 20:18 UTC, Lunarmagpie commented on pincer/middleware/interaction_create.py
> -    await interaction.build()
Fixed

2021-11-01 20:18 UTC, Lunarmagpie commented on pincer/objects/guild/guild.py
> -        """
Rewrote the docs

2021-11-01 20:18 UTC, Lunarmagpie commented on pincer/utils/__init__.py
> -    "APINullable", "APIObject", "Choices", "Coro", "Descripted",
Fixed

2021-11-01 20:26 UTC, Arthurdw approved these changes
~ Runs without exceptions for me

2021-11-01 20:46 UTC, trag1c approved these changes

2021-11-01 21:19 UTC, Lunarmagpie requested changes
Guess Ill go fix all the problems now :(

2021-11-01 21:19 UTC, Lunarmagpie commented on pincer/objects/guild/channel.py
> +    from ...client import Client
These imports are a mess

2021-11-01 21:19 UTC, Lunarmagpie commented on pincer/objects/guild/guild.py
> +    from .role import Role
These imports are a mess

2021-11-01 21:19 UTC, Lunarmagpie commented on pincer/objects/guild/invite.py
> +    from ..app.application import Application
`..app.application` should be above `...utils`

2021-11-01 21:19 UTC, Lunarmagpie commented on pincer/objects/message/component.py
> +    from ..app.select_menu import SelectOption
import order should be changed

2021-11-01 21:19 UTC, Lunarmagpie commented on pincer/objects/message/context.py
> +    from ..app.command import ClientCommandStructure
should be higher

2021-11-01 21:30 UTC, Lunarmagpie approved these changes

2021-11-01 22:16 UTC, trag1c approved these changes

2021-11-01 23:16 UTC, trag1c approved these changes

2021-11-02 09:08 UTC, Arthurdw approved these changes

2021-11-02 11:20 UTC, Arthurdw commented
Aight so I found a few things while quickly looking at the preview:
```
client.py:

Client.throttler missing : in defaults notation.
@event, load_cog docs rename botclient to myclient

commands.py:

update to descripted in command decorator example
document keep in remove_command & remove_commands
```

2021-11-02 18:28 UTC, Sigmanificient approved these changes

2021-11-02 19:45 UTC, Lunarmagpie commented
> Aight so I found a few things while quickly looking at the preview:
> 
> ```
> client.py:
> 
> Client.throttler missing : in defaults notation.
> @event, load_cog docs rename botclient to myclient
> 
> commands.py:
> 
> update to descripted in command decorator example
> document keep in remove_command & remove_commands
> ```

I've made all of the changes.

2021-11-03 17:24 UTC, Sigmanificient approved these changes

2021-11-04 03:03 UTC, Endercheif approved these changes

2021-11-05 05:13 UTC, Endercheif approved these changes

2021-11-05 10:47 UTC, Arthurdw requested changes
We  are almost there! 💖

2021-11-05 10:47 UTC, Arthurdw commented on pincer/__init__.py
> +__version__ = "0.9.3a"
It seems like your changed has been reverted :/

2021-11-05 10:47 UTC, Arthurdw commented on pincer/__init__.py
> +__version__ = "0.9.3a"
It seems like your change has been reverted :/
Can you undo the revert?

2021-11-05 17:13 UTC, Lunarmagpie commented on pincer/__init__.py
> +__version__ = "0.9.3a"
I've made the change. :)

2021-11-06 01:48 UTC, Endercheif commented
@ooliver1 originally, I recall you changing the import of `__version__` to RegEx. Why was that?

In the [latest commit](https://github.com/Pincer-org/Pincer/commit/4124eefebf082a0519f2bb151c7cc1a51c3d577b) by @Lunarmagpie it was "reverted" back. Do you believe we should keep the change or not?

2021-11-06 04:22 UTC, Lunarmagpie commented
> @ooliver1 originally, I recall you changing the import of `__version__` to RegEx. Why was that?
> 
> In the [latest commit](https://github.com/Pincer-org/Pincer/commit/4124eefebf082a0519f2bb151c7cc1a51c3d577b) by @Lunarmagpie it was "reverted" back. Do you believe we should keep the change or not?

Yeah, it was kinda broken. I thought it would be better to import directly than rewrite the regex whenever that part of `__init__.py` changed.

2021-11-06 09:02 UTC, ooliver1 commented
I did try to import but it would say weird stuff on readthedocs about importing outside top level package, I could try again though

2021-11-06 11:05 UTC, Arthurdw requested changes

2021-11-06 11:05 UTC, Arthurdw commented on pincer/middleware/interaction_create.py
> +        self, command, context, interaction, kwargs)
If your're putting it like this, put the `)` on a newline.

2021-11-06 18:39 UTC, trag1c approved these changes

2021-11-06 21:11 UTC, Arthurdw approved these changes

2021-11-06 22:25 UTC, Lunarmagpie approved these changes

2021-11-08 15:05 UTC, merged

2021-11-08 15:07 UTC, ooliver1 commented
:0 just looking at gh at school ayo

2021-11-08 15:33 UTC, Sigmanificient commented
Seems like doc built wrongly xD