:sparkles: Middleware addition
Pincer-org/Pincer pull request #163
Opened 2021-10-24 05:25 UTC by Endercheif

### Changes

-   `adds`: 
    - `on_channel_delete`
    - `on_channel_pins_update`
    - `on_channel_update`
    - `on_guild_delete`
    - `on_guild_update`
    - `on_message_reaction_add`
    - `on_message_reaction_remove`
    - `on_message_reaction_remove_all`
    - `on_message_reaction_remove_emoji`
    - `on_thread_create`
    - `on_thread_delete`
    - `on_thread_list_sync`
    - `on_thread_member_update`
    - `on_thread_members_update`
    - `on_thread_update`

 ### Check off the following

-   [x] I have tested my changes with the current requirements
-   [x] My Code follows the pep8 code style.

2021-10-31 04:36 UTC, Endercheif commented
dont review yet. im just fixing that last commit

2021-10-31 04:56 UTC, Endercheif commented
fixed

2021-10-31 05:58 UTC, Endercheif commented
commit was wacky. I'm fixing it

2021-10-31 11:37 UTC, Arthurdw commented
https://app.codacy.com/gh/Pincer-org/Pincer/pullRequest?prid=8299424

2021-10-31 22:45 UTC, Endercheif commented
> 
> 
> https://app.codacy.com/gh/Pincer-org/Pincer/pullRequest?prid=8299424

@Arthurdw 👍

2021-11-01 18:09 UTC, Arthurdw requested changes

2021-11-01 18:09 UTC, Arthurdw commented on pincer/middleware/channel_delete.py
> +    return "on_channel_delete", [
If client has the channel guild cached, remove the channel from that guild.

2021-11-01 18:09 UTC, Arthurdw commented on pincer/middleware/channel_update.py
> +    return "on_channel_update", [
If client has the channel guild cached, update channel.

2021-11-01 18:09 UTC, Arthurdw commented on pincer/middleware/guild_delete.py
> +
Delete guild from client cache

2021-11-01 18:09 UTC, Arthurdw commented on pincer/middleware/guild_update.py
> +
Update guild in client cache

2021-11-01 18:09 UTC, Arthurdw commented on pincer/middleware/guild_update.py
> +    ]
Use mapping

2021-11-01 18:09 UTC, Arthurdw commented on pincer/middleware/thread_list_sync.py
> +    ]
Use mapping

2021-11-01 18:09 UTC, Arthurdw commented on pincer/middleware/thread_list_sync.py
> +    ]
Use mapping

2021-11-01 18:09 UTC, Arthurdw commented on pincer/middleware/thread_members_update.py
> +    ]
Use mapping

2021-11-01 18:09 UTC, Arthurdw commented on pincer/objects/events/channel.py
> +    )
Post init's arn't required on `APIObject`'s as these should get casted automatically.

2021-11-01 18:09 UTC, Arthurdw commented on pincer/objects/message/emoji.py
> +    id: Optional[Snowflake] = None
Use `APINullable` & `MISSING` for optional parameters.

2021-11-04 02:23 UTC, Endercheif commented
@Arthurdw can this be merged?

2021-11-05 10:49 UTC, Arthurdw approved these changes

2021-11-08 22:52 UTC, merged