🔖 Pincer 0.10.0
Pincer-org/Pincer pull request #175
Opened 2021-11-03 22:59 UTC by Sigmanificient

+ proper closing/restart
+ ack & ctx interaction
+ Descripted
+ Type Casting
+ Gateaway compression
+ Guild member middleware
+ New str defaults
+ Invite link property
+ Message delete_after
+ Guild registeration
+ Discord changes
+ Emoji reaction functions
+ BugFixes

2021-11-03 23:28 UTC, trag1c requested changes

2021-11-03 23:28 UTC, trag1c commented on pincer/objects/message/user_message.py
> +    edited_timestamp: APINullable[Timestamp] = MISSING
duplicate variable

2021-11-03 23:28 UTC, trag1c commented on docs/CONTRIBUTING.md
>  help organization them by categories.
```suggestion
helps to organize them by categories.
```

2021-11-05 10:56 UTC, Arthurdw approved these changes

2021-11-05 16:49 UTC, trag1c approved these changes

2021-11-06 06:03 UTC, Endercheif requested changes
For every thing that is "new" (post #155 ), the docstrings need to be changed to the numpy docstyle.

2021-11-06 06:03 UTC, Endercheif commented on setup.cfg
> +# Development Status :: 3 - Alpha
is pincer an alpha now?

2021-11-06 10:59 UTC, Arthurdw commented on setup.cfg
> +# Development Status :: 3 - Alpha
no, its in pre-alpha

2021-11-07 19:05 UTC, Sigmanificient commented on pincer/objects/message/user_message.py
> +        :param emoji:
This will be fixed with #155

2021-11-07 19:07 UTC, Sigmanificient commented on pincer/utils/convert_message.py
> +    PILLOW_IMPORT = False
i think `PILLOW_IMPORT` might be less confusing

2021-11-07 19:08 UTC, Sigmanificient commented on pincer/objects/message/user_message.py
> +        :param emoji:
Doc style will be fixed with #155

2021-11-07 19:12 UTC, merged