🧪 Added a test to check for Guild deserialization
Pincer-org/Pincer pull request #226
Opened 2021-11-16 23:19 UTC by Lunarmagpie

### Changes
Adds a failing test :( and fixes some of the testing stuff to make it easier to use. (Added missing dependency and removed code coverage being show by default)
The test works a little different the code
```python
52    # This is not how channels are passed into Guild.from_dict in the code. A
53    # Channel object is passed in instead. I haven't done that here because the
54    # Guild.from_dict() method expects a Dict without APIObjects in it.
55    # The code should be changed to reflect that once this test is made passing.
```
I believe leaving that's a problem in our code base so the test doesn't expect how things are done right now.

 ### Check off the following

-   [x] I have tested my changes with the current requirements
-   [x] My Code follows the pep8 code style.

2021-11-17 20:50 UTC, Endercheif approved these changes

2021-11-20 20:45 UTC, Lunarmagpie commented
I decided to go fix the issues. All tests pass and I've tested [this](https://pastebin.com/4Smgigp0) with no exceptions/unexpected results. I sorta confident everything works perfectly.

2021-11-20 20:47 UTC, Sigmanificient commented
> I decided to go fix the issues. All tests pass and I've tested [this](https://pastebin.com/4Smgigp0) with no exceptions/unexpected results. I sorta confident everything works perfectly.

You are a legend!

2021-11-21 19:37 UTC, Endercheif requested changes

2021-11-21 19:37 UTC, Endercheif commented on pincer/utils/conversion.py
> +    Client : Optional[:class:`~pincer.client.Client`]
Change these parameters to lowercase

2021-11-22 03:34 UTC, Endercheif approved these changes

2021-11-22 04:52 UTC, Lunarmagpie commented
I'm pretty sure sigma is ok with the changes and Arthur had a few days to review but didn't so I'm merging this 🙏

2021-11-22 04:52 UTC, merged