Audio/v2
Pincer-org/Pincer pull request #228
Opened 2021-11-17 06:51 UTC by VincentRPS

### Changes

-   `adds`: Opus Voice Support

 ### Check off the following

-   [ ] I have tested my changes with the current requirements
-   [x] My Code follows the pep8 code style.

2021-11-17 07:46 UTC, VincentRPS commented
This is a very hard task to do So i am planning for this to be ready by 0.12~ish

2021-11-17 08:25 UTC, VincentRPS commented
TODO: ``fix up voice_client some imports are non-existence and don't have contents they want``

2021-11-17 12:24 UTC, Lunarmagpie requested changes
Additionally there's also style problems. We don't type hint None and I think a lot of docs are missing.
Also how did you test it? I dont see a way to access this for a Client.

2021-11-17 12:24 UTC, Lunarmagpie commented on pincer/exceptions.py
> +class ClientException(PincerError):
I think this needs a better name

2021-11-17 12:24 UTC, Lunarmagpie commented on pincer/exceptions.py
> +class ConnectionClosed(PincerError):
Same with this one. Should mention that it has to do with voice.

2021-11-17 12:24 UTC, Lunarmagpie commented on pincer/exceptions.py
You don't need to say when an Exception was introduced.

2021-11-17 12:24 UTC, Lunarmagpie commented on pincer/oggparse.py
> +This is a modified version of discord.py's OggParse module
Incorrect liscence header. Look at any other file in the lib and copy the style for all of your files.

2021-11-17 12:24 UTC, Lunarmagpie commented on pincer/oggparse.py
> +from typing import TYPE_CHECKING, ClassVar, IO, Generator, Tuple, Optional
Type checking import should be used for type hints.

2021-11-17 12:24 UTC, Lunarmagpie commented on pincer/oggparse.py
> +        except Exception:
Check to make exception less broad.

2021-11-17 12:24 UTC, Lunarmagpie commented on pincer/oggparse.py
> +class OggError(PincerError):
This should be in the exceptions file since it looks like the user has a way to catch it.

2021-11-17 12:24 UTC, Lunarmagpie commented on pincer/types/user.py
> +"""
There's already a class for this too

2021-11-17 12:24 UTC, Lunarmagpie commented on pincer/types/voice.py
> +The MIT License (MIT)
I'm pretty confident we created classes for all of this already

2021-11-17 12:24 UTC, Lunarmagpie commented on pincer/voice_client.py
> +        An abstract method that is called when the client's voice state
This isn't an abstract method

2021-11-17 12:24 UTC, Lunarmagpie commented on pincer/voice_client.py
> +        """Optional[:class:`Guild`]: The guild we're connected to, if applicable."""
Doc class typehints use the full path. Look in any file for an example.

2021-11-17 12:27 UTC, VincentRPS commented
@Lunarmagpie i haven't tested it yet, i've not added the http stuff and gateway cause it takes a long time to do that i am working on it though

2021-11-18 04:26 UTC, VincentRPS commented
i've been trying to get websockets to work with voice data but have been unable to-do it for now i'm gonna close this and if/when i find a way to-do so i will reopen this pr

2021-11-18 04:26 UTC, closed without merging

2021-11-21 15:08 UTC, ooliver1 commented
Why not set to draft or smth

2021-11-21 15:15 UTC, VincentRPS commented
> Why not set to draft or smth

It was?

2021-11-21 17:34 UTC, Sigmanificient commented
The repository that submitted this pull request has been deleted...

2021-11-30 00:30 UTC, RPSMain commented
> The repository that submitted this pull request has been deleted...

I accidentally changed the main branch so I had to refork