Removing `_http` passing and getting it from the client
Pincer-org/Pincer pull request #272
Opened 2021-11-29 22:34 UTC by Sigmanificient

See #266

2021-11-29 22:36 UTC, Lunarmagpie commented
I vote for this but it needs to be fixed everywhere that uses _http

2021-11-29 22:40 UTC, Sigmanificient commented
> I vote for this but it needs to be fixed everywhere that uses _http

This is the role of the second commit, expect if i missed any other

2021-11-29 23:21 UTC, RPSMain commented
Couldn’t you just remove _client.http or would that be harder?

2021-11-30 01:43 UTC, Lunarmagpie commented
`_client.http` is how `_http` is set in the first place

2021-11-30 03:01 UTC, Endercheif requested changes

2021-11-30 03:01 UTC, Endercheif commented on pincer/objects/guild/guild.py
> +            Channel.from_dict({**i, "_client": client})
use `construct_client_dict` instead

2021-11-30 03:01 UTC, Endercheif commented on pincer/objects/guild/member.py
> +        return cls.from_dict({**data, "_client": client})
use `construct_client_dict` instead

2021-11-30 21:04 UTC, trag1c approved these changes

2021-11-30 21:04 UTC, trag1c commented on pincer/objects/guild/member.py
> +from typing import TYPE_CHECKING, T
Why?

2021-11-30 21:07 UTC, Endercheif requested changes

2021-11-30 21:07 UTC, Endercheif commented on pincer/objects/guild/member.py
> +from typing import TYPE_CHECKING, T
```suggestion
from typing import TYPE_CHECKING
```

2021-12-01 03:24 UTC, Lunarmagpie approved these changes

2021-12-01 03:25 UTC, Lunarmagpie commented on pincer/objects/guild/member.py
> +from typing import TYPE_CHECKING, T
Commit this since the import was unused

2021-12-01 20:47 UTC, Endercheif approved these changes

2021-12-01 20:54 UTC, merged

2021-12-01 20:55 UTC, Arthurdw reviewed
~ Seems fine