:sparkles: Added Webhook related endpoints
Pincer-org/Pincer pull request #281
Opened 2021-11-30 21:47 UTC by trag1c

### Adds
> `Client.get_webhook`
`Channel.get_webhooks`
`Guild.get_webhooks`
`WebhookCompatibility` enum
`Webhook.edit`
`Webhook.delete`
`Webhook.execute`
`Webhook.execute_github`
`Webhook.execute_slack`
`Webhook.get_message`
`Webhook.delete_mesage`
`Webhook.edit_message`
`Webhook.from_id`

### Improvements
> Parameter formatting in `Channel.edit`

 ### Check off the following

-   [x] I have tested my changes with the current requirements
-   [x] My Code follows the pep8 code style.

2021-11-30 22:01 UTC, Sigmanificient requested changes

2021-11-30 22:14 UTC, Lunarmagpie commented on pincer/objects/guild/channel.py
> +        for webhook_data in data:
```suggestion
        for webhook_data in await self._http.get(f"channels/{self.id}/webhooks"):
```

2021-11-30 22:23 UTC, trag1c commented on pincer/objects/guild/channel.py
> +        for webhook_data in data:
Too long

2021-11-30 22:26 UTC, Lunarmagpie requested changes

2021-11-30 22:26 UTC, Lunarmagpie commented on pincer/objects/guild/guild.py
> +        for webhook_data in data:
```suggestion
        for webhook_data in await self._http.get(f"guilds/{self.id}/webhooks"):
```

2021-11-30 22:26 UTC, Lunarmagpie commented on pincer/objects/guild/webhook.py
> +    async def delete(self, token: Optional[str] = None) -> None:
`-> None` isn't needed

2021-11-30 22:26 UTC, Lunarmagpie commented on pincer/objects/guild/webhook.py
> +    ) -> None:
```suggestion
    ) -> Webhook:
```

2021-11-30 22:26 UTC, Lunarmagpie commented on pincer/objects/guild/webhook.py
> +    ) -> None:
`-> None` isn't needed

2021-11-30 22:26 UTC, Lunarmagpie commented on pincer/objects/guild/webhook.py
> +        message_id: Snowflake,
Are you able to use `self.id` for this?

2021-11-30 22:26 UTC, Lunarmagpie commented on pincer/objects/guild/webhook.py
> +        message_id: Snowflake,
Are you able to use `self.id` for this?

2021-11-30 22:28 UTC, trag1c commented on pincer/objects/guild/webhook.py
> +        message_id: Snowflake,
Yeah

2021-11-30 22:29 UTC, Lunarmagpie commented on pincer/objects/guild/webhook.py
> +        message_id: Snowflake,
resolving cause i did the same thing twice lol

2021-12-01 18:07 UTC, trag1c commented on pincer/objects/guild/webhook.py
> +    Slack = "/slack"
Yes

2021-12-01 20:52 UTC, Endercheif requested changes

2021-12-01 20:52 UTC, Endercheif commented on pincer/exceptions.py
> +
Add `EmbedOverflow` to `__init__.py`

2021-12-02 19:46 UTC, Lunarmagpie approved these changes

2021-12-02 22:37 UTC, Sigmanificient approved these changes

2021-12-03 01:08 UTC, Endercheif approved these changes
<3

2021-12-03 01:37 UTC, merged