:sparkles: Adding ScheduleEvent
Pincer-org/Pincer pull request #304
Opened 2021-12-12 20:42 UTC by Sigmanificient

### Changes

-   `adds`: ScheduleEvent

 ### Check off the following

-   [x] I have tested my changes with the current requirements
-   [x] My Code follows the pep8 code style.

2021-12-12 20:58 UTC, Lunarmagpie requested changes
I think this file should be renamed to `scheduled_events.py`

2021-12-12 20:58 UTC, Lunarmagpie commented on pincer/objects/guild/schedule_events.py
> +    privacy_level: :class:`PrivacyLevel`
```suggestion
    privacy_level: :class:`~pincer.guild.stage.PrivacyLevel`
```

2021-12-12 20:58 UTC, Lunarmagpie commented on pincer/objects/guild/schedule_events.py
> +    status: :class:`EventStatus`
```suggestion
    status: :class:`~pincer.guild.schedule_events.EventStatus`
```

2021-12-12 20:58 UTC, Lunarmagpie commented on pincer/objects/guild/schedule_events.py
> +    entity_type: :class:`GuildScheduledEventEntityType`
```suggestion
    entity_type: :class:`~pincer.guild.schedule_events.GuildScheduledEventEntityType`
```

2021-12-12 20:58 UTC, Lunarmagpie commented on pincer/objects/guild/schedule_events.py
> +    creator: :class:`User`
```suggestion
    creator: :class:`~pincer.objects.user.user.User`
```

2021-12-13 13:16 UTC, nerdguyahmad requested changes

2021-12-14 00:01 UTC, Lunarmagpie approved these changes

2021-12-14 22:27 UTC, VincentRPS approved these changes

2021-12-14 23:10 UTC, trag1c requested changes

2021-12-14 23:10 UTC, trag1c commented on pincer/objects/guild/scheduled_events.py
> +class GuildScheduledEventEntityType(Enum):
```suggestion
class GuildScheduledEventEntityType(IntEnum):
```

2021-12-14 23:10 UTC, trag1c commented on pincer/objects/guild/scheduled_events.py
> +    privacy_level = PrivacyLevel
```suggestion
    privacy_level: PrivacyLevel
```

2021-12-14 23:10 UTC, trag1c commented on pincer/objects/guild/guild.py
> +from .scheduled_events import ScheduledEvent
Move to ~L32

2021-12-14 23:10 UTC, trag1c commented on pincer/objects/guild/scheduled_events.py
> +from ...utils.types import APINullable
```suggestion
from typing import Optional, TYPE_CHECKING
from ...utils.api_object import APIObject, MISSING

if TYPE_CHECKING:
    from ..guild.stage import PrivacyLevel
    from ..user import User
    from ...utils.snowflake import Snowflake
    from ...utils.timestamp import Timestamp
    from ...utils.types import APINullable
```

2021-12-15 21:35 UTC, trag1c approved these changes

2021-12-16 00:46 UTC, merged