Add timeouts.
Pincer-org/Pincer pull request #324
Opened 2021-12-22 10:33 UTC by ooliver1

### Changes

-   `adds`: Attribute to ``GuildMember`` and param to ``Guild.modify_member``
-   `fixed`: ...
-   `improvements`: ...

 ### Check off the following

-   [x] I have tested my changes with the current requirements
-   [x] My Code follows the pep8 code style.

I have no idea how pincer works really

2021-12-22 10:39 UTC, VincentRPS approved these changes

2021-12-22 10:41 UTC, ooliver1 commented on setup.cfg
> +    Programming Language :: Python :: 3.10
was a workflow, dont ask me

2021-12-23 01:50 UTC, Lunarmagpie requested changes

2021-12-23 01:50 UTC, Lunarmagpie commented on pincer/objects/guild/guild.py
> +            kwargs.pop("communication_disabled_until", None)
I don't think this is required. If it is replace it with
```suggestion
        if kwargs.get("communication_disabled_until") is MISSING:
            kwargs.pop("communication_disabled_until")
```

2021-12-23 08:50 UTC, Endercheif approved these changes

2021-12-23 17:07 UTC, Sigmanificient commented on setup.cfg
> +    Programming Language :: Python :: 3.10
np

2021-12-23 17:07 UTC, Sigmanificient approved these changes

2021-12-23 23:08 UTC, Lunarmagpie requested changes

2021-12-23 23:08 UTC, Lunarmagpie commented on pincer/objects/guild/guild.py
> +        communication_disabled_until: Optional[Timestamp] = None,
```suggestion
        communication_disabled_until: Optional[Timestamp] = MISSING,
```

2021-12-23 23:09 UTC, merged