:bug: ActivityFlags no longer crash
Pincer-org/Pincer pull request #339
Opened 2021-12-31 06:44 UTC by Lunarmagpie

I got so annoyed that I finally fixed it
ActivityFlags are sent as a number with multiple flags in it. Pretty sure I did the bitwise to get the bool right.

 ### Check off the following

-   [x] I have tested my changes with the current requirements
-   [x] My Code follows the pep8 code style.

2021-12-31 21:03 UTC, Sigmanificient requested changes

2021-12-31 21:07 UTC, Lunarmagpie commented on pincer/objects/events/presence.py
> +@dataclass
The free `repr` is worth keeping the dataclass for

2022-01-01 01:30 UTC, Endercheif approved these changes

2022-01-01 15:17 UTC, trag1c commented on pincer/objects/events/presence.py
> +    EMBEDDED: bool
Don't think this is needed if there's an overriding `__init__`

2022-01-01 21:43 UTC, Lunarmagpie commented
Maybe i should remove the dataclass :skull: 
i think the usage was unpythonic anyway

2022-01-02 00:17 UTC, Lunarmagpie commented
dataclass is gone

2022-01-02 00:26 UTC, merged