:sparkles: Added an imager welcome example
Pincer-org/Pincer pull request #453
Opened 2022-04-06 18:56 UTC by Arthurdw

A new example which shows how you would make a member welcomer, this example also shows a way on how you can import all cogs from a directory. 
![image](https://user-images.githubusercontent.com/38541241/162184018-770c8568-4a51-48d8-8f71-e8df68ef62eb.png)

Variant:
![image](https://user-images.githubusercontent.com/38541241/162183991-39a0d3ca-8b77-406f-9c4c-41c213ba3c99.png)

### Changes

-   `adds`: A welcome example

 ### Check off the following

-   [x] I have tested my changes with the current requirements
-   [x] My code follows the pep8 code style.

2022-04-06 19:28 UTC, Sigmanificient commented on examples/discord-welcomer/cogs/welcome.py
> +        with open("./cogs/templates/welcome.html", "r") as f:
```suggestion
        with open("./cogs/templates/welcome.html") as f:
```

2022-04-06 19:32 UTC, Sigmanificient requested changes

2022-04-06 19:32 UTC, Sigmanificient commented on examples/discord-welcomer/cogs/welcome.py
> +        with open("./cogs/templates/welcome.html", "r") as f:
```suggestion
        with open("./cogs/templates/welcome.html") as f:
```

2022-04-06 19:32 UTC, Sigmanificient commented on examples/discord-welcomer/main.py
> +                            "Successfully loaded %s (%s)" % (definition, container))
```suggestion
                            "Successfully loaded %s (%s)" % (definition, container)
                        )
```

2022-04-06 19:32 UTC, Sigmanificient commented on examples/discord-welcomer/cogs/templates/welcome.html
> +            border: 4px solid #ffd53d;
```suggestion
            border: 4px solid white;
```

2022-04-06 19:33 UTC, Arthurdw commented on examples/discord-welcomer/cogs/templates/welcome.html
> +            border: 4px solid #ffd53d;
Why?

2022-04-06 19:35 UTC, Sigmanificient commented on examples/discord-welcomer/cogs/templates/welcome.html
> +            border: 4px solid #ffd53d;
match the white title color

2022-04-06 19:38 UTC, Arthurdw commented on examples/discord-welcomer/cogs/templates/welcome.html
> +            border: 4px solid #ffd53d;
Pincer theme tho :/

2022-04-06 19:38 UTC, Arthurdw commented on examples/discord-welcomer/cogs/templates/welcome.html
> +            border: 4px solid #ffd53d;
Pincer theme tho :/

2022-04-07 15:54 UTC, Sigmanificient approved these changes

2022-04-09 07:56 UTC, merged