Methods to Guild and User
Pincer-org/Pincer pull request #73
Opened 2021-09-23 02:30 UTC by Endercheif

### Changes

-   `adds`: These methods
    - `Client.get_user`
    - `Guild.get_member`
    - `Guild.modify_member`
    - `User.from_id`

> Note: This will not work without #72 being merged

 ### Check off the following

-   [x] I have tested my changes with the current requirements
-   [x] My Code follows the pep8 code style.

2021-09-23 02:58 UTC, Endercheif commented
Codacy says "method already defined line 519"

for that method, the duplicate is just a function that is typed with the `@typing.overload` decorator. This is to increase the quality of the code since the function relies on a dictionary and by using `**kwargs` instead of listing it, the arguments it can be directly passed in to the api.

2021-09-23 07:16 UTC, Sigmanificient requested changes

2021-09-23 07:16 UTC, Sigmanificient commented on pincer/objects/guild.py
> +    async def modify_member(self, *, _id: int, nick: Optional[str] = None, roles: Optional[List[Snowflake]] = None, mute: Optional[bool] = None, deaf: Optional[bool] = None, channel_id: Optional[Snow
Please ensure pep8 & E501 with 80 characters wrapping

2021-09-23 07:16 UTC, Sigmanificient commented on pincer/objects/guild.py
> +    :param _client:
> Can you fill the params for `_client` & `_http`?

2021-09-23 07:16 UTC, Sigmanificient commented on pincer/objects/guild.py
> +
> Can you add the return info with the __doc__ please?

2021-09-23 07:16 UTC, Sigmanificient commented on pincer/objects/user.py
> +    :param _client:
> Can you fill the params for `_client` & `_http`?

2021-09-23 07:16 UTC, Sigmanificient commented on pincer/objects/user_message.py
> +    :param _client:
> Can you fill the params for `_client` & `_http`?

2021-09-23 07:16 UTC, Sigmanificient commented on pincer/utils/conversion.py
> +                else factory(v) if client is None else factory(v | {"_client": client, "_http": client.http})
> pep8 & 501 also don't apply here

2021-09-23 07:16 UTC, Sigmanificient commented on pincer/utils/conversion.py
> +                else factory(v) if client is None else factory(v | {"_client": client, "_http": client.http})
Tho i would chain ternary as it make the readibility super hard

2021-09-23 07:16 UTC, Sigmanificient commented on pincer/middleware/error.py
> +    return "on_error", [DiscordError.from_dict({"_client": self, "_http": self.http} | payload.data)]
pep8 & 501 also don't apply here

may want to put 
```py
return "on_error",  [
    DiscordError.from_dict(
        {"_client": self, "_http": self.http} | payload.data
    )
]

```

2021-09-23 07:16 UTC, Sigmanificient commented on pincer/middleware/interaction_create.py
> +    interaction: Interaction = Interaction.from_dict(payload.data | {"_client": self, "_http": self.http })
pep8 & 501 also don't apply here

may want to put
```py
interaction: Interaction = Interaction.from_dict(
    payload.data | {"_client": self, "_http": self.http }
)
```

2021-09-23 07:16 UTC, Sigmanificient commented on pincer/middleware/message_delete.py
> +    return "on_message_delete", [MessageDeleteEvent.from_dict({"_client": self, "_http": self.http} | payload.data)]
pep8 & 501 also don't apply here

may want to put 
```py
return "on_message_delete", [
    MessageDeleteEvent.from_dict(
        {"_client": self, "_http": self.http} | payload.data
    )
]

```

2021-09-23 07:16 UTC, Sigmanificient commented on pincer/middleware/ready.py
> +    self.bot = User.from_dict({"_client": self, "_http": self.http} | payload.data.get("user"))
pep8 & 501 also don't apply here

may want to put 
```py
self.bot = User.from_dict(
    {"_client": self, "_http": self.http} | payload.data.get("user")
)
```

2021-09-23 12:40 UTC, Endercheif commented on pincer/objects/guild.py
> +    hub_type: APINullable[...] = MISSING # TODO: Add type when type is known
It is not in the docs but comes in the api. I assume it's new

2021-09-23 13:31 UTC, Endercheif commented on pincer/objects/guild.py
> +    hub_type: APINullable[...] = MISSING # TODO: Add type when type is known
similarly, `nsfw` is not in the docs but comes in the api

2021-09-24 06:13 UTC, Sigmanificient approved these changes

2021-09-24 06:15 UTC, merged